export default Object.freeze({
  DASHBOARD: "dashboard",
  CHAT: "chat",
  EDIT_PROFILE: "EditProfile",
  PROFILE: "profile",
  NOTIFICATION: "notification",
  SEARCH_RESULTS: "searchResults",
  WELCOME: "welcome",
  LOGIN: "LoginScreen",
  UNDER_RECEIVER_ORDERS: "UnderReceive",
  UNDER_PROCESS_ORDERS: "UnderProcess",
  DELAYED_ORDERS: "Delayed",
  STATISTICS_PAGE: "StatisticsPage",
  DISCLOSURES: "Disclosures",
  ORDER_DETAILS: "OrderDetails",
  CHANGE_PASSWORD: "ChangePassword",
  CHAT_MODEL: "ChatModel",
  PDF_VIEW: "pdfView",
  DASHBOARD_LIST: "dashboardList",
});
